### ISSUE TITLE
Could you tell me which version of yolov3 is used?

### ISSUE THREAD

**Issue by sgq123** [kevaldoshi17/NVIDIA_AICITY#1]

**Comment by kevaldoshi17** [comment]
It's Yolov3-416. The weights and cfg files were downloaded from here: https://github.com/AlexeyAB/darknet

**Comment by sgq123** [comment]
> It's Yolov3-416. The weights and cfg files were downloaded from here: https://github.com/AlexeyAB/darknet

thank you!
