### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by HanwenCao** [kevaldoshi17/NVIDIA_AICITY#2]
```
from kneed import KneeLocator
ModuleNotFoundError: No module named 'kneed'
```
It seems that a module is missing. Please correct me if I am wrong. Thank you.

**Comment by kevaldoshi17** [comment]
Hello, 

It is not a module but rather a library that you need to install.

More details available [here](https://pypi.org/project/kneed/)

**Comment by HanwenCao** [comment]
Yes! Thank you.
