### ISSUE TITLE
How Can I make Detector.py works with any Dataset ?

### ISSUE THREAD

**Issue by Nizar4790k** [kevaldoshi17/NVIDIA_AICITY#5]
Hello, I almost finishing implementing this model but I have problems to make Detector.py works with any Dataset .

**Comment by kevaldoshi17** [comment]
HI, you'll have to be more specific as to what you mean by any dataset. This code should work for detecting anomalies in videos where the anomalies are caused due to an object stopping or leaving its predefined path.
